export const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const RATES = {
  CASHFLOW_CAPITAL_RETURN: 15,
  EXCHANGE_RATE_VALUE: 1790,
  EXCHANGE_RATE_CURRENCY: 'USD',
  INVESTMENT_TOKEN_VALUE: 10,
  MINIMUM_WITHDRAWAL: 5,
  MINIMUM_DURATION_CASHFLOW: 15,
  MINIMUM_INVESTMENT: 5,
  MINIMUM_CASHFLOW_INVESTMENT: 100,
  MINIMUM_GROWTH_INVESTMENT: 500,
  MINIMUM_SAVING: 5,
  WITHDRAWAL_CHARGE_PERCENTAGE: 5,
  SAVINGS_RATE_VALUE: 6.5,
  REFERRAL_RATE: 2,
  ADD_CARD_AMOUNT: 100,
  ADD_CARD_AMOUNT_DOLLAR: 1,
  NO_OF_CARDS_ALLOWED: 3,
  SAVINGS_INTEREST_RATE: 3,
  SECONDARY_TIME_CAP: 3,
  SECONDARY_CHARGE_RATE_BELOW_1K: 10,
  SECONDARY_CHARGE_RATE_ABOVE_1K: 20,
  SECONDARY_AMOUNT_THRESHOLD: 50,
  SECONDARY_DURATION: 12,
  COURIER_RATE_PER_KILOMETER: 300,
};

export const LIMITS = {
  MAXIMUM_WALLET_CREDIT_INCOMPLETE_KYC: 100,
  MAXIMUM_INVESTMENT_INCOMPLETE_KYC: 100,
};

export const REDIRECTS = {
  WALLET: process.env.NODE_ENV === 'development' ? '' : '',
  ORDERS: process.env.NODE_ENV === 'development' ? '' : '',
  ACCOUNT: process.env.NODE_ENV === 'development' ? '' : '',
  INVESTMENT: process.env.NODE_ENV === 'development' ? '' : '',
};
